import { Cell } from './cell';

//temporary while setting up the generation code
export const CELLS: Cell[][] = [
    [{ displayNumber: 1, correctNumber: 1, isInitial: true }, { displayNumber: 2, correctNumber: 1, isInitial: true }, { displayNumber: 3, correctNumber: 1, isInitial: true }, { displayNumber: 4, correctNumber: 1, isInitial: true }, { displayNumber: 5, correctNumber: 1, isInitial: true }, { displayNumber: 6, correctNumber: 1, isInitial: true }, { displayNumber: 7, correctNumber: 1, isInitial: true }, { displayNumber: 8, correctNumber: 1, isInitial: true }, { displayNumber: 9, correctNumber: 1, isInitial: true }],
    [{ displayNumber: 1, correctNumber: 1, isInitial: true }, { displayNumber: 2, correctNumber: 1, isInitial: true }, { displayNumber: 3, correctNumber: 1, isInitial: true }, { displayNumber: 4, correctNumber: 1, isInitial: true }, { displayNumber: 5, correctNumber: 1, isInitial: true }, { displayNumber: 6, correctNumber: 1, isInitial: true }, { displayNumber: 7, correctNumber: 1, isInitial: true }, { displayNumber: 8, correctNumber: 1, isInitial: true }, { displayNumber: 9, correctNumber: 1, isInitial: true }],
    [{ displayNumber: 1, correctNumber: 1, isInitial: true }, { displayNumber: 2, correctNumber: 1, isInitial: true }, { displayNumber: 3, correctNumber: 1, isInitial: true }, { displayNumber: 4, correctNumber: 1, isInitial: true }, { displayNumber: 5, correctNumber: 1, isInitial: true }, { displayNumber: 6, correctNumber: 1, isInitial: true }, { displayNumber: 7, correctNumber: 1, isInitial: true }, { displayNumber: 8, correctNumber: 1, isInitial: true }, { displayNumber: 9, correctNumber: 1, isInitial: true }],
    [{ displayNumber: 1, correctNumber: 1, isInitial: true }, { displayNumber: 2, correctNumber: 1, isInitial: true }, { displayNumber: 3, correctNumber: 1, isInitial: true }, { displayNumber: 4, correctNumber: 1, isInitial: true }, { displayNumber: 5, correctNumber: 1, isInitial: true }, { displayNumber: 6, correctNumber: 1, isInitial: true }, { displayNumber: 7, correctNumber: 1, isInitial: true }, { displayNumber: 8, correctNumber: 1, isInitial: true }, { displayNumber: 9, correctNumber: 1, isInitial: true }],
    [{ displayNumber: 1, correctNumber: 1, isInitial: true }, { displayNumber: 2, correctNumber: 1, isInitial: true }, { displayNumber: 3, correctNumber: 1, isInitial: true }, { displayNumber: 4, correctNumber: 1, isInitial: true }, { displayNumber: 5, correctNumber: 1, isInitial: true }, { displayNumber: 6, correctNumber: 1, isInitial: true }, { displayNumber: 7, correctNumber: 1, isInitial: true }, { displayNumber: 8, correctNumber: 1, isInitial: true }, { displayNumber: 9, correctNumber: 1, isInitial: true }],
    [{ displayNumber: 1, correctNumber: 1, isInitial: true }, { displayNumber: 2, correctNumber: 1, isInitial: true }, { displayNumber: 3, correctNumber: 1, isInitial: true }, { displayNumber: 4, correctNumber: 1, isInitial: true }, { displayNumber: 5, correctNumber: 1, isInitial: true }, { displayNumber: 6, correctNumber: 1, isInitial: true }, { displayNumber: 7, correctNumber: 1, isInitial: true }, { displayNumber: 8, correctNumber: 1, isInitial: true }, { displayNumber: 9, correctNumber: 1, isInitial: true }],
    [{ displayNumber: 1, correctNumber: 1, isInitial: true }, { displayNumber: 2, correctNumber: 1, isInitial: true }, { displayNumber: 3, correctNumber: 1, isInitial: true }, { displayNumber: 4, correctNumber: 1, isInitial: true }, { displayNumber: 5, correctNumber: 1, isInitial: true }, { displayNumber: 6, correctNumber: 1, isInitial: true }, { displayNumber: 7, correctNumber: 1, isInitial: true }, { displayNumber: 8, correctNumber: 1, isInitial: true }, { displayNumber: 9, correctNumber: 1, isInitial: true }],
    [{ displayNumber: 1, correctNumber: 1, isInitial: true }, { displayNumber: 2, correctNumber: 1, isInitial: true }, { displayNumber: 3, correctNumber: 1, isInitial: true }, { displayNumber: 4, correctNumber: 1, isInitial: true }, { displayNumber: 5, correctNumber: 1, isInitial: true }, { displayNumber: 6, correctNumber: 1, isInitial: true }, { displayNumber: 7, correctNumber: 1, isInitial: true }, { displayNumber: 8, correctNumber: 1, isInitial: true }, { displayNumber: 9, correctNumber: 1, isInitial: true }],
    [{ displayNumber: 1, correctNumber: 1, isInitial: true }, { displayNumber: 2, correctNumber: 1, isInitial: true }, { displayNumber: 3, correctNumber: 1, isInitial: true }, { displayNumber: 4, correctNumber: 1, isInitial: true }, { displayNumber: 5, correctNumber: 1, isInitial: true }, { displayNumber: 6, correctNumber: 1, isInitial: true }, { displayNumber: 7, correctNumber: 1, isInitial: true }, { displayNumber: 8, correctNumber: 1, isInitial: true }, { displayNumber: 9, correctNumber: 1, isInitial: true }]
];
